'$schema' = 'https://starship.rs/config-schema.json'

username.show_always = true
username.format = '[$user]($style)@'
username.style_user = 'bold green'
hostname.ssh_only = false
hostname.format = '[$hostname]($style):'
hostname.style ='bold green'
directory.style = 'bold blue'
directory.truncate_to_repo = false
status.format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '

dotnet.format = '❯ [$symbol($version )(\($tfm\))]($style) '

username.disabled = false
hostname.disabled = false
localip.disabled = true
shlvl.disabled = true
singularity.disabled = true
kubernetes.disabled = true
directory.disabled = false
vcsh.disabled = true
fossil_branch.disabled = true
fossil_metrics.disabled = true
git_branch.disabled = false
git_commit.disabled = false
git_state.disabled = false
git_metrics.disabled = false
git_status.disabled = false
hg_branch.disabled = true
pijul_channel.disabled = true
docker_context.disabled = true
package.disabled = false
c.disabled = true
cmake.disabled = false
cobol.disabled = true
daml.disabled = true
dart.disabled = true
deno.disabled = false
dotnet.disabled = false
elixir.disabled = true
elm.disabled = true
erlang.disabled = true
fennel.disabled = true
gleam.disabled = true
golang.disabled = false
guix_shell.disabled = true
haskell.disabled = true
haxe.disabled = true
helm.disabled = true
java.disabled = true
julia.disabled = true
kotlin.disabled = true
gradle.disabled = true
lua.disabled = true
nim.disabled = true
nodejs.disabled = false
ocaml.disabled = true
opa.disabled = true
perl.disabled = true
php.disabled = true
pulumi.disabled = true
purescript.disabled = true
python.disabled = false
quarto.disabled = true
raku.disabled = true
rlang.disabled = true
red.disabled = true
ruby.disabled = true
rust.disabled = true
scala.disabled = true
solidity.disabled = true
swift.disabled = true
terraform.disabled = true
typst.disabled = true
vlang.disabled = true
vagrant.disabled = true
zig.disabled = true
buf.disabled = true
nix_shell.disabled = true
conda.disabled = true
meson.disabled = true
spack.disabled = true
memory_usage.disabled = true
aws.disabled = true
gcloud.disabled = true
openstack.disabled = true
azure.disabled = true
nats.disabled = true
direnv.disabled = true
crystal.disabled = true
sudo.disabled = true
cmd_duration.disabled = false
line_break.disabled = false
jobs.disabled = true
battery.disabled = true
time.disabled = true
status.disabled = false
os.disabled = true
container.disabled = true
shell.disabled = true
